
The following have been reloaded with a version change:
  1) devel/cuda/12.2 => devel/cuda/12.4

2025-02-04 10:53:33.251679: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-02-04 10:53:33.362930: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1738662813.408782 1880214 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1738662813.420933 1880214 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-02-04 10:53:33.507173: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
INFO:root:Starting serial dataset generation...
2025-02-04 10:53:38.307655: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2025-02-04 10:53:38.307717: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:137] retrieving CUDA diagnostic information for host: haicn1708.localdomain
2025-02-04 10:53:38.307731: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:144] hostname: haicn1708.localdomain
2025-02-04 10:53:38.307832: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:168] libcuda reported version is: 550.54.15
2025-02-04 10:53:38.307860: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:172] kernel reported version is: 550.54.15
2025-02-04 10:53:38.307869: I external/local_xla/xla/stream_executor/cuda/cuda_diagnostics.cc:259] kernel version seems to match DSO: 550.54.15
INFO:root:Generating dataset: Number of obs 100 | Replication 0
INFO:root:Saved X to ../data_generation/output_local/X_n_100_rep_0.npy
INFO:root:Saved linear_effects to ../data_generation/output_local/linear_effects_n_100_rep_0.npy
INFO:root:Saved Z to ../data_generation/output_local/Z_n_100_rep_0.npy
INFO:root:Saved nonlinear_effects to ../data_generation/output_local/nonlinear_effects_n_100_rep_0.npy
INFO:root:Saved images to ../data_generation/output_local/images_n_100_rep_0.npy
INFO:root:Generated X, Z and images: Number of obs 100 | Replication 0
Traceback (most recent call last):
  File "/hkfs/home/haicore/scc/pa6512/PySSDR/data_generation/data_generation.py", line 281, in <module>
    scenarios_generate(n_list, distribution_list, SNR_list, grid_size, alpha_l, beta_nl, n_rep=100, n_cores=n_core,
  File "/hkfs/home/haicore/scc/pa6512/PySSDR/data_generation/data_generation.py", line 239, in scenarios_generate
    generate_task(n_sample=i, distribution_list=distribution_list,
  File "/hkfs/home/haicore/scc/pa6512/PySSDR/data_generation/data_generation.py", line 196, in generate_task
    unstructured_effects, U_k, psi_k, b_k = generate_unstructured_effects(flattened_images, dnn_model, K)
  File "/hkfs/home/haicore/scc/pa6512/PySSDR/data_generation/data_generation.py", line 93, in generate_unstructured_effects
    penultimate_layer_model = Model(inputs=dnn_model.input, outputs=dnn_model.layers[-2].output)
  File "/software/all/jupyter/ai/2025-01-14/lib/python3.9/site-packages/keras/src/ops/operation.py", line 254, in input
    return self._get_node_attribute_at_index(0, "input_tensors", "input")
  File "/software/all/jupyter/ai/2025-01-14/lib/python3.9/site-packages/keras/src/ops/operation.py", line 285, in _get_node_attribute_at_index
    raise AttributeError(
AttributeError: The layer sequential has never been called and thus has no defined input.
cp: cannot stat '/scratch/slurm_tmpdir/job_1497201/output': No such file or directory
